---
# certificate for kubebox.dev.doc.network
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: buddy-certificate
  namespace: m3test
spec:
  secretName: buddy-certificate
  issuerRef:
    name: letsencrypt-docnetwork
    kind: ClusterIssuer
  dnsNames:
  - buddy.m3test.doc.network

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buddy
  annotations:
    external-dns.aplpha.kubernetes.io/hostname: buddy.m3test.doc.network
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  namespace: m3test

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - buddy.m3test.doc.network
    secretName: buddy-certificate
  rules:
  - host: buddy.m3test.doc.network
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: buddy
            port:
              number: 8501

